<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  
  <ItemGroup>
    <Reference Include="Sharpen.Managed">
      <HintPath>..\Sharpen.Managed.Output\Sharpen.Managed.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
